// <auto-generated />
using System;
using System.Collections.Generic;
using Bibosio.ProductsModule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bibosio.ProductsModule.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product")
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bibosio.ProductsModule.Domain.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUseShortName")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUseValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Values")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Option", "product");
                });

            modelBuilder.Entity("Bibosio.ProductsModule.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Products", "product");
                });

            modelBuilder.Entity("Bibosio.ProductsModule.Domain.Option", b =>
                {
                    b.HasOne("Bibosio.ProductsModule.Domain.Product", null)
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Bibosio.ProductsModule.Domain.Product", b =>
                {
                    b.OwnsOne("Bibosio.ProductsModule.Domain.ValueObjects.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("Bibosio.ProductsModule.Domain.Product", b =>
                {
                    b.Navigation("ProductOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
